#!/usr/bin/expect -f

# Command file for expect
# https://linux.die.net/man/1/expect

set timeout -1

spawn "ed25519"

expect "Enter passphrase (empty for no passphrase): "
send -- "\n"

expect "Enter same passphrase again: "
send -- "\n"

interact